### ISSUE TITLE
this mod causes deathpoints to not work in xaero's minimap

### ISSUE THREAD

**Issue by nickademas** [Fesaa/AutoSprintFix#1]
Minecraft 1.20.4
Fabric loader 0.15.6

**Comment by Fesaa** [comment]
That would make sense. This mod does it in a quite destructive way. I'll have a look if I can do it more appropriately, between studying. 
Thanks for the report!

**Comment by Fesaa** [comment]
Well, this took way too long to do. I haven't tested it as xaero's minimap hasn't released their version for 1.20.5 yet. But it should work, normally. 

Sorry for the delay. xo
